// Querying Images API
export const GET_IMAGES = 'GET_IMAGES'
export const RECEIEVE_IMAGES = 'RECEIEVE_IMAGES'
export const ERROR_RECEIVING_IMAGES = 'ERROR_RECEIVING_IMAGES'
export const GET_MORE_IMAGES = 'GET_MORE_IMAGES'
export const RECEIEVE_MORE_IMAGES = 'RECEIEVE_MORE_IMAGES'
export const ERROR_RECEIVING_MORE_IMAGES = 'ERROR_RECEIVING_MORE_IMAGES'

// Controlled search query input
export const SET_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY'
export const CLEAR_SEARCH_QUERY = 'CLEAR_SEARCH_QUERY'

// Selecting a photo to see details
export const SELECT_PHOTO = 'SELECT_PHOTO'
export const DESELECT_PHOTO = 'DESELECT_PHOTO'
